<a href="https://colab.research.google.com/github/deepankar-pathak1/Some_Programming_Stuff/blob/main/Basic_Error_In_Pyhton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.random.rand(3,2)
b = np.random.rand(3,2)
print(a)
print("****")
print(b)

[[0.59942981 0.28111277]
 [0.76428936 0.40917965]
 [0.22741257 0.49110492]]
****
[[0.42877541 0.44097256]
 [0.53604386 0.51266674]
 [0.03193599 0.17126687]]


In [3]:
# x = []
# for i in a:
#   for j in i:
#     x.append(j)
# print(x)

# y = []

# for k in b:
#   for l in k:
#     y.append(l)

# print(y)



In [4]:
# Shape 
a.shape # It means that we are calling an attribute from a which is shape

(3, 2)

In [5]:
# If we do This :- It will generate an error because shape is not a function ---> a.shape()
# a.shape() # 'tuple' object is not callable

In [6]:
# Type
# print(a.type()) # Genrate an Error 'numpy.ndarray' object has no attribute 'type' because a does not have an attribute called type
# Read Referance --> https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html

In [7]:
print(type(a))

<class 'numpy.ndarray'>


In [8]:
print(a.shape)
print(b.shape)

(3, 2)
(3, 2)


In [9]:
# Add both the matrix using for loop
(x,y) = a.shape
print(x,y)

3 2


In [10]:
c = np.zeros((3,2))
for i in range(x):
  for j in range(y):
   c[i,j] = a[i,j] + b[i,j]

print(c)

[[1.02820522 0.72208533]
 [1.30033322 0.9218464 ]
 [0.25934856 0.66237179]]


In [11]:
# Finding Points whether they lies inside or outside the circle
# With split these number will be transformed into string, so we have to convert them into integer
px,py = map(int, input("Enter Two Number Seperated by Comma-> ").split(","))

Enter Two Number Seperated by Comma-> 2,2


In [13]:
cx,cy,r = map(int, input("Enter Center Point X,Y and Radious").split(","))

Enter Center Point X,Y and Radious3,5,3


In [14]:
import math

d = math.sqrt((px-cx)**2 + (py-cy)**2)

In [15]:
if d<r:
  print(f"Point Lies inside the circle, Radious->{r} and Distance->{d}")
elif d==r:
  print(f"Point Lies on the circle")
else:
  print("POint lies Outside the circle")

POint lies Outside the circle


In [16]:
# reshape using pyhton
a1 = np.random.rand(4,5)
print(a1)

[[0.8459834  0.77545705 0.13026299 0.76726417 0.52406466]
 [0.60586424 0.52972838 0.30567455 0.59688063 0.1820215 ]
 [0.8745746  0.589637   0.28010459 0.49883193 0.98905934]
 [0.52415878 0.38033803 0.71286687 0.2450139  0.31700488]]


In [20]:
print(np.reshape(a1,(20),'F')) # F means Coloumn major order

[0.8459834  0.60586424 0.8745746  0.52415878 0.77545705 0.52972838
 0.589637   0.38033803 0.13026299 0.30567455 0.28010459 0.71286687
 0.76726417 0.59688063 0.49883193 0.2450139  0.52406466 0.1820215
 0.98905934 0.31700488]


In [21]:
print(np.reshape(a1,(20),'C')) # C means Row major order

[0.8459834  0.77545705 0.13026299 0.76726417 0.52406466 0.60586424
 0.52972838 0.30567455 0.59688063 0.1820215  0.8745746  0.589637
 0.28010459 0.49883193 0.98905934 0.52415878 0.38033803 0.71286687
 0.2450139  0.31700488]


In [23]:
print(np.reshape(a1,(5,-1),'C')) # -1 automatically transformed order in 20 --> 5*4

[[0.8459834  0.77545705 0.13026299 0.76726417]
 [0.52406466 0.60586424 0.52972838 0.30567455]
 [0.59688063 0.1820215  0.8745746  0.589637  ]
 [0.28010459 0.49883193 0.98905934 0.52415878]
 [0.38033803 0.71286687 0.2450139  0.31700488]]


In [24]:
# Tensor 4*5*6 convert it into 10*12
b1 = np.random.rand(4,5,6)

In [26]:
print(np.reshape(b1,(10,12),'C'))

[[0.08387744 0.64794058 0.70589256 0.6757823  0.16238509 0.89505217
  0.08322252 0.61400698 0.91965699 0.65132618 0.21866127 0.22187499]
 [0.89294637 0.48239165 0.98537192 0.11857048 0.92055125 0.42169922
  0.86721095 0.89121397 0.01669481 0.02237795 0.56036198 0.76558508]
 [0.90340949 0.28064009 0.64010499 0.92095004 0.78184631 0.32757589
  0.42147976 0.78307591 0.37131868 0.41124542 0.82983241 0.88851069]
 [0.91551834 0.76211476 0.81744626 0.29556913 0.2246153  0.24902053
  0.1750282  0.95559671 0.28153826 0.74013657 0.23430897 0.3542103 ]
 [0.13997199 0.45933311 0.33596869 0.22486133 0.06784976 0.52213539
  0.52408522 0.0351209  0.66064245 0.03317128 0.93664019 0.17239247]
 [0.34992642 0.69092938 0.81885062 0.37951692 0.478158   0.07771734
  0.93244495 0.31904638 0.11813067 0.97159277 0.8687955  0.18633741]
 [0.83753779 0.6356029  0.57292462 0.66084105 0.2012612  0.95251114
  0.94901193 0.6012889  0.14036891 0.89994101 0.42255071 0.8019001 ]
 [0.8312253  0.2662943  0.79295834 0.5021

In [27]:
a1 = np.random.rand(3,4)
a2 = np.random.rand(3,5)

In [29]:
c1 = np.hstack((a1,a2))
print(c1)

[[0.49434382 0.54038003 0.67863214 0.06422495 0.91418619 0.04810654
  0.77283439 0.93440876 0.03083972]
 [0.5042637  0.79206641 0.33199179 0.87955973 0.33683941 0.92469032
  0.26775838 0.24865764 0.71389555]
 [0.86914216 0.89601121 0.83071659 0.31763102 0.79427367 0.86639452
  0.41288101 0.95017914 0.89917365]]


In [31]:
a3 = np.random.rand(5,4)
c2 = np.vstack((a1,a3))
print(c2)

[[0.49434382 0.54038003 0.67863214 0.06422495]
 [0.5042637  0.79206641 0.33199179 0.87955973]
 [0.86914216 0.89601121 0.83071659 0.31763102]
 [0.24153187 0.02805362 0.78898654 0.48462615]
 [0.70132719 0.25556219 0.93558346 0.65925002]
 [0.1737418  0.51538458 0.96186749 0.0205414 ]
 [0.93287893 0.56832893 0.31761365 0.81668341]
 [0.70582399 0.2472199  0.08589442 0.34829201]]


In [35]:
x1 = np.random.rand(5,4,3)
x2 = np.random.rand(5,3,3)

y1 = np.hstack((x1,x2))
# y1