<a href="https://colab.research.google.com/github/deepankar-pathak1/Some_Programming_Stuff/blob/main/Numpy_Prac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np
print(np.__version__)
print(np.show_config)

1.18.5
<function show at 0x7fb5f952c1e0>


In [27]:
# Write a NumPy program to test whether none of the elements of a given array is zero.

import numpy as np
x = np.array([1,2,3])
print("Original Array : ")
print(x)
print(np.all(x))
y = np.array([0,1])
print(np.all(y))

Original Array : 
[1 2 3]
True
False


In [29]:
# to create 1D array 

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
print(np.repeat(True,9).reshape(3,-1))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [33]:
arr = np.arange(10)
print(arr)
print("Check Odd ")
odd = arr[arr%2 != 0]
print(odd)

[0 1 2 3 4 5 6 7 8 9]
Check Odd 
[1 3 5 7 9]


In [35]:
b = np.arange(20)
print(b)
print("Replace all Odd Number with -1")
b[b%2 != 0] = -1
print(b)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Replace all Odd Number with -1
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]


In [39]:
# reshape an array
c = np.arange(20)
print(c)
d = np.reshape(c,(5,4))
print("******--*****--****")
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
******--*****--****
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
